baseURL = 'https://isaiahdavis.com/'
languageCode = 'en-US'
title = 'Isaiah Davis - Portfolio'
theme = 'myPortfolio'

[params]
  description = "Personal portfolio website for Isaiah Davis. Showcasing projects, blog posts, and contact information."
  author = "Isaiah Davis"

# [[menus.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10

# [[menus.main]]
# name = 'Portfolio'
# pageRef = '/portfolio'
# weight = 15

# [[menus.main]]
# name = 'Blog'
# pageRef = '/posts'
# weight = 20

# [[menus.main]]
# name = 'About'
# pageRef = '/about'
# weight = 30

# [[menus.main]]
# name = 'Contact'
# pageRef = '/contact'
# weight = 40
